name: Build and release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build for Linux
      run: GOOS=linux GOARCH=amd64 go build -o venjector-linux .

    - name: Build for Darwin
      run: GOOS=darwin GOARCH=amd64 go build -o venjector-darwin .

    - name: Build for Windows
      run: GOOS=windows GOARCH=amd64 go build -o venjector-windows.exe .

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Upload Release Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: venjector
        path: |
          venjector-linux
          venjector-darwin
          venjector-windows.exe
